// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHwmgt6hj37rzVZDNhrSvz2Xary-zk97o',
    appId: '1:833527299104:web:7c453497d9300664059045',
    messagingSenderId: '833527299104',
    projectId: 'login-excercise-8873b',
    authDomain: 'login-excercise-8873b.firebaseapp.com',
    storageBucket: 'login-excercise-8873b.appspot.com',
    measurementId: 'G-Y269PXVJVB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8C-o56-X4lOjN_gg-ieoBHXw0-_V5t0M',
    appId: '1:833527299104:android:e863b6b03d9bdf79059045',
    messagingSenderId: '833527299104',
    projectId: 'login-excercise-8873b',
    storageBucket: 'login-excercise-8873b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQjhd-UESQKYGlb_F3dO2oZxWmCfhSCAg',
    appId: '1:833527299104:ios:d1e559c1026f1115059045',
    messagingSenderId: '833527299104',
    projectId: 'login-excercise-8873b',
    storageBucket: 'login-excercise-8873b.appspot.com',
    iosClientId: '833527299104-pg4m3kr2p8peisochbm34qe8hb0pu8nc.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginExcerise',
  );
}
